version: "3"
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  app:
    image: url-shortener
    ports:
      - 5000:5000
    depends_on:
      - mongo

